autoInstallPeers: false
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 432000

packages:
  - ./
  - ./playground

onlyBuiltDependencies:
  - esbuild
