packages:
  - ./
  - ./playground

catalogs:
  deps:
    '@nuxt/kit': ^3.19.3
    defu: ^6.1.4
    knitwork: ^1.2.0
    nitro-better-auth: ^0.1.1
    pathe: ^2.0.3
  dev:
    '@aa900031/eslint-config': ^3.2.0
    '@aa900031/release-it-config': ^0.1.0
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint-config': ^1.9.0
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^3.19.3
    '@nuxt/test-utils': ^3.19.2
    '@vitest/coverage-istanbul': ^3.2.4
    eslint: ^9.38.0
    nuxt: ^3.19.3
    release-it: ^19.0.5
    vitest: ^3.2.4
  peer:
    better-auth: ^1.3.27
  types:
    '@types/node': ^20.19.22
    typescript: ~5.9.3
    vue-tsc: ^2.2.12

onlyBuiltDependencies:
  - esbuild
