autoInstallPeers: false
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 432000

packages:
  - ./
  - ./playground

minimumReleaseAgeExclude:
  - nitro-better-auth@0.3.1

allowBuilds:
  esbuild: true
  unrs-resolver: true
